### ISSUE TITLE
ReferenceError: value is not defined

### ISSUE THREAD

**Issue by ukmoose** [sebleedelisle/rpi-led-control#1]
When I try to run a setChar example I get the following error:

> var v = charTable[value] || charTable[value.toLowerCase()];//.toString(16)];
>                         ^
> ReferenceError: value is not defined

This relates to line 315 of the api-led-control.js where "value" needs to be replaced by "char"

**Comment by sebleedelisle** [comment]
Ooops, my bad. A bit of untested refactoring. Just pushed a fix for this.

**Comment by sebleedelisle** [comment]
Oh and also included a text example.

**Comment by ukmoose** [comment]
Ta!
